name = "TestPicker"
uuid = "a64165b9-4409-4de6-85cd-a4e0953bae44"
authors = ["theogf <theo.galyfajou@gmail.com> and contributors"]
version = "2.2.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"
bat_jll = "e1736374-6498-5d90-ab12-e7e58ba27d07"
fzf_jll = "214eeab7-80f7-51ab-84ad-2988db7cef09"

[compat]
InteractiveUtils = "1"
JuliaSyntax = "0.4, 1"
Markdown = "1"
Pkg = "1"
PrecompileTools = "1"
REPL = "1"
Revise = "3"
Test = "1"
TestEnv = "1"
bat_jll = "13.0.0"
fzf_jll = "0.61"
julia = "1.10"
